version : 2
updates :
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit : 10
    labels :
      - "type/dependencies"

  - package-ecosystem : terraform
    directory : "audit/"
    schedule :
      interval : weekly
    open-pull-requests-limit : 10
    labels :
      - "type/dependencies"

  - package-ecosystem : terraform
    directory : "tencent/ap-chengdu-1/production"
    schedule :
      interval : daily
    open-pull-requests-limit : 10
    labels :
      - "type/dependencies"

  - package-ecosystem : terraform
    directory : "tencent/ap-chengdu-2/production"
    schedule :
      interval : daily
    open-pull-requests-limit : 10
    labels :
      - "type/dependencies"

  - package-ecosystem : terraform
    directory : "tencent/ap-hongkong-2/production"
    schedule :
      interval : daily
    open-pull-requests-limit : 10
    labels :
      - "type/dependencies"

  - package-ecosystem : terraform
    directory : "tencent/ap-shanghai-4/production"
    schedule :
      interval : daily
    open-pull-requests-limit : 10
    labels :
      - "type/dependencies"

  - package-ecosystem : terraform
    directory : "dns/1234.link"
    schedule :
      interval : weekly
    open-pull-requests-limit : 10
    labels :
      - "type/dependencies"

  - package-ecosystem : terraform
    directory : "dns/16345.net"
    schedule :
      interval : weekly
    open-pull-requests-limit : 10
    labels :
      - "type/dependencies"

  - package-ecosystem : terraform
    directory : "dns/bluerbook.cn"
    schedule :
      interval : weekly
    open-pull-requests-limit : 10
    labels :
      - "type/dependencies"

  - package-ecosystem : terraform
    directory : "dns/kuaishov.com"
    schedule :
      interval : weekly
    open-pull-requests-limit : 10
    labels :
      - "type/dependencies"

  - package-ecosystem : terraform
    directory : "dns/lianhe.art"
    schedule :
      interval : weekly
    open-pull-requests-limit : 10
    labels :
      - "type/dependencies"

  - package-ecosystem : terraform
    directory : "dns/lianhehuyu.com"
    schedule :
      interval : weekly
    open-pull-requests-limit : 10
    labels :
      - "type/dependencies"

  - package-ecosystem : terraform
    directory : "dns/yunsixun.cn"
    schedule :
      interval : weekly
    open-pull-requests-limit : 10
    labels :
      - "type/dependencies"

  - package-ecosystem : terraform
    directory : "dns/yunsixun.com"
    schedule :
      interval : weekly
    open-pull-requests-limit : 10
    labels :
      - "type/dependencies"

  - package-ecosystem : terraform
    directory : "github/"
    schedule :
      interval : weekly
    open-pull-requests-limit : 10
    labels :
      - "type/dependencies"